---
# defaults file for Nagios_Installation
#

nagios_admin_pass: password

nagios_version: 4.4.6

make_list:
    - all
    - install-groups-users
    - install
    - install-daemoninit
    - install-commandmode
    - install-config
    - install-webconf

extra_configure_args: ""
