---
# defaults file for Nagios_Installation
#

nagios_admin_pass: password

nagios_version: 4.4.6
nagios_plugins_version: 2.3.3

make_list:
    - all
    - install-groups-users
    - install
    - install-daemoninit
    - install-commandmode
    - install-config
    - install-webconf

extra_configure_args: ""

task_list:
    - install_core
    - install_plugins
    - configure_nagios
