---
plugin_pkg_list:
        - gcc
        - glibc
        - glibc-common
        - make
        - gettext
        - automake
        - autoconf
        - wget
        - openssl-devel
        - net-snmp
        - net-snmp-utils
        - epel-release
