---
plugin_pkg_list:
        - gcc 
        - glibc 
        - glibc-common
        - make
        - gettext
        - automake
        - autoconf
        - wget 
        - openssl-devel
        - net-snmp 
        - net-snmp-utils
        - epel-release
        - perl-Net-SNMP

pkg_list:
        - httpd
        - php
        - php-cli
        - gcc
        - unzip
        - wget
        - glibc
        - glibc-common
        - gd
        - gd-devel
        - net-snmp
        - ":Development Tools"
