---
plugin_pkg_list:
        - gcc 
        - glibc 
        - glibc-common
        - make
        - gettext
        - automake
        - autoconf
        - wget 
        - openssl-devel
        - net-snmp 
        - net-snmp-utils
        - epel-release
        - perl-Net-SNMP
        - python3-passlib

pkg_list:
        - gcc
        - glibc
        - glibc-common
        - perl
        - httpd
        - php
        - wget
        - gd
        - gd-devel

apache_user: "apache"
apache2_service: "httpd.service"
