---
- name: Install dependencies for building Nagios Plugins {{ nagios_plugins_version }}
  package:
    name: "{{ pkg_name }}"
    state: latest
  become: yes
  loop: "{{ plugin_pkg_list }}"
  loop_control:
    loop_var: pkg_name

- name: Create Nagios User
  user:
    name: nagios
    state: present
  become: yes

- name: Include distribution-specific prep
  include_tasks: "{{ ansible_distribution }}.yml"
