---
# tasks file for Nagios_Installation

- name: Include distribution variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Run Nagios-Core Installation
  include_tasks: install_nagios_core.yml
  when: '"install_core" in install_list'

- name: Run Nagios-Plugins installation
  include_tasks: install_nagios_plugins.yml
  when: '"install_plugins" in install_list'
